"""Reading controller: passage delivery, answer auto-grading, band mapping."""

from __future__ import annotations

from typing import Any

from fastapi import HTTPException, status
from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from core.band_mapping import reading_band
from models.content import Passage, Question
from models.reading import ReadingAttempt
from models.user import User

from db.repository import OwnedRepository

from .adaptive_controller import resolve_difficulty

from .base import CamelModel
from .grading import is_correct
from .weakness_controller import WeaknessService

#: Ownership-checked reads. Returns 404 rather than 403 for someone
#: else's row, so an id cannot be confirmed by a stranger.
_attempts = OwnedRepository(ReadingAttempt, label="Attempt")


# ---------- Schemas ----------
class QuestionPublic(CamelModel):
    id: str
    type: str
    prompt: str
    options: list[str] | None = None


class PassageResponse(CamelModel):
    id: str
    title: str
    body: str
    exam_type: str
    difficulty: str
    topic: str | None
    word_count: int
    questions: list[QuestionPublic]


class ReadingSubmitRequest(CamelModel):
    passage_id: str
    answers: dict[str, Any]


class PerQuestionResult(CamelModel):
    question_id: str
    type: str
    correct: bool
    submitted: Any
    correct_answer: Any
    explanation: str | None


class ReadingResultResponse(CamelModel):
    attempt_id: str
    passage_id: str
    raw_score: int
    total_questions: int
    band: float
    per_question: list[PerQuestionResult]


# ---------- Seeding (dev/demo content) ----------
_SEED_BODY = (
    "Tea is one of the most widely consumed beverages in the world. According to "
    "historical records, tea originated in China, where it was first used as a "
    "medicinal drink thousands of years ago. Over time it spread along trade "
    "routes to the rest of Asia and, eventually, to Europe. The processing of the "
    "leaves determines the type of tea: green tea is barely oxidized, whereas "
    "black tea is produced by allowing the leaves to oxidize fully. Today, tea is "
    "cultivated in dozens of countries and remains central to many cultures."
)


_SEED_BODY_SLEEP = (
    "Sleep is far from a passive state. Across the night the brain cycles "
    "through light sleep, deep sleep and REM sleep, and each stage serves a "
    "different purpose. Deep sleep supports physical repair, while memory "
    "consolidation takes place largely during REM sleep, when the brain replays "
    "and reorganises the day's experiences. Levels of melatonin, a hormone that "
    "promotes drowsiness, rise in the evening as light fades. Most adults "
    "function best on seven to nine hours a night, although the exact "
    "requirement varies between individuals."
)

_SEED_BODY_URBAN = (
    "Urban green spaces have become central to city planning. Research across "
    "several large cities shows that parks and tree cover measurably lower air "
    "pollution and surface temperatures, offsetting the heat generated by "
    "concrete and traffic. Shade from mature trees also reduces the cooling "
    "costs of nearby buildings during summer. Beyond the physical effects, "
    "residents living within walking distance of a park report higher levels of "
    "physical activity and lower stress. Critics note, however, that new parks "
    "can raise property values and displace long-standing communities."
)


_SEED_BODY_MARKET = (
    "Farmers' markets have become a familiar sight in towns across the country. "
    "At a farmers' market, growers sell their produce directly to the public "
    "rather than through a supermarket. Shoppers say they like being able to ask "
    "where food comes from, and many enjoy the atmosphere on a Saturday morning. "
    "Prices are not always lower than in the shops, but the fruit and vegetables "
    "are usually picked within a day or two of being sold, so they stay fresh for "
    "longer. Most markets open early and close by lunchtime. Some now accept card "
    "payments, though a number of smaller stalls still ask for cash."
)


async def _seed_easy_passage(session: AsyncSession) -> None:
    """Add the easy passage and its questions.

    Split out so it can run on a database that was seeded before easy content
    existed. Without this, selecting Easy silently serves a medium passage.
    """
    passage = Passage(
        title="Farmers' Markets",
        body=_SEED_BODY_MARKET,
        exam_type="academic",
        difficulty="easy",
        topic="food",
        word_count=len(_SEED_BODY_MARKET.split()),
        source="seed",
    )
    session.add(passage)
    await session.flush()
    session.add_all(
        [
            Question(
                passage_id=passage.id,
                order_index=1,
                type="mcq",
                prompt="Who sells the produce at a farmers' market?",
                options=[
                    "Supermarket buyers",
                    "The growers themselves",
                    "Government inspectors",
                    "Delivery drivers",
                ],
                correct_answer="The growers themselves",
                explanation=(
                    "The passage says growers sell directly to the public rather "
                    "than through a supermarket."
                ),
                difficulty="easy",
            ),
            Question(
                passage_id=passage.id,
                order_index=2,
                type="true_false_notgiven",
                prompt="Farmers' markets are always cheaper than supermarkets.",
                options=["true", "false", "not_given"],
                correct_answer="false",
                explanation=(
                    "The passage states prices are not always lower than in the "
                    "shops."
                ),
                difficulty="easy",
            ),
            Question(
                passage_id=passage.id,
                order_index=3,
                type="short_answer",
                prompt="By what time of day do most markets close?",
                options=None,
                correct_answer="lunchtime",
                explanation="The passage says most markets close by lunchtime.",
                difficulty="easy",
            ),
        ]
    )
    await session.flush()


_SEED_BODY_HEADINGS = (
    "A. For most of human history, ice was a local luxury. It could be cut from "
    "frozen lakes in winter and packed in sawdust, but it melted long before it "
    "could travel far. Only the wealthy, and only in cold regions, ate anything "
    "chilled.\n\n"
    "B. That changed in the nineteenth century, when merchants began shipping "
    "lake ice across oceans in insulated holds. A trade that started as a "
    "curiosity grew into a substantial industry, and ice harvested in New England "
    "was sold in India and the Caribbean.\n\n"
    "C. Mechanical refrigeration eventually made the harvest obsolete. Compressors "
    "could produce ice anywhere, at any time of year, and the vast ice houses that "
    "had lined northern rivers were abandoned within a generation.\n\n"
    "D. The consequences reached far beyond drinks. Reliable cold allowed meat, "
    "dairy and vaccines to be moved over long distances, reshaping what people ate "
    "and how far medicine could travel."
)

_HEADINGS = [
    "A trade built on natural ice",
    "How cold changed diets and medicine",
    "Why early ice stayed local",
    "The technology that ended an industry",
    "The cost of transporting goods",
]


async def _seed_matching_headings_passage(session: AsyncSession) -> None:
    """A passage exercising the matching-headings question type.

    Modelled as one question per paragraph sharing a single heading list, which
    is exactly a grouped multiple choice — so the existing grading path applies
    unchanged and no new answer shape is introduced.
    """
    passage = Passage(
        title="The Ice Trade",
        body=_SEED_BODY_HEADINGS,
        exam_type="academic",
        difficulty="medium",
        topic="history",
        word_count=len(_SEED_BODY_HEADINGS.split()),
        source="seed",
    )
    session.add(passage)
    await session.flush()

    # More headings than paragraphs, as in the real exam: the distractor is what
    # makes the task a test of comprehension rather than elimination.
    answers = [
        ("Paragraph A", "Why early ice stayed local"),
        ("Paragraph B", "A trade built on natural ice"),
        ("Paragraph C", "The technology that ended an industry"),
        ("Paragraph D", "How cold changed diets and medicine"),
    ]
    session.add_all(
        [
            Question(
                passage_id=passage.id,
                order_index=index,
                type="matching_headings",
                prompt=f"Choose the best heading for {label}.",
                options=list(_HEADINGS),
                correct_answer=answer,
                explanation=f"{label} is summarised by “{answer}”.",
                difficulty="medium",
            )
            for index, (label, answer) in enumerate(answers, start=1)
        ]
    )
    await session.flush()


async def _ensure_seeded(session: AsyncSession) -> None:
    existing = {
        difficulty
        for (difficulty,) in (
            await session.execute(select(Passage.difficulty).distinct())
        ).all()
    }
    has_headings = await session.scalar(
        select(func.count())
        .select_from(Question)
        .where(Question.type == "matching_headings")
    )

    if existing:
        # Already seeded, but possibly from a bank that predates this content.
        # Checked per addition rather than "is the table empty", so anything
        # added later still reaches databases seeded earlier.
        if "easy" not in existing:
            await _seed_easy_passage(session)
        if not has_headings:
            await _seed_matching_headings_passage(session)
        return

    await _seed_easy_passage(session)
    await _seed_matching_headings_passage(session)
    passage = Passage(
        title="The History of Tea",
        body=_SEED_BODY,
        exam_type="academic",
        difficulty="medium",
        topic="history",
        word_count=len(_SEED_BODY.split()),
        source="seed",
    )
    session.add(passage)
    await session.flush()
    session.add_all(
        [
            Question(
                passage_id=passage.id,
                order_index=1,
                type="mcq",
                prompt="According to the passage, where did tea originate?",
                options=["India", "China", "Japan", "England"],
                correct_answer="China",
                explanation="The passage states tea originated in China.",
                difficulty="medium",
            ),
            Question(
                passage_id=passage.id,
                order_index=2,
                type="true_false_notgiven",
                prompt="Tea was first used as a medicinal drink.",
                options=["true", "false", "not_given"],
                correct_answer="true",
                explanation="The text says it was first used as a medicinal drink.",
                difficulty="medium",
            ),
            Question(
                passage_id=passage.id,
                order_index=3,
                type="short_answer",
                prompt="Which tea is produced by allowing the leaves to oxidize fully?",
                options=None,
                correct_answer="black",
                explanation="Black tea is produced by full oxidation of the leaves.",
                difficulty="medium",
            ),
        ]
    )

    # A second medium passage so learners at the same level get variety.
    sleep = Passage(
        title="The Science of Sleep",
        body=_SEED_BODY_SLEEP,
        exam_type="academic",
        difficulty="medium",
        topic="health",
        word_count=len(_SEED_BODY_SLEEP.split()),
        source="seed",
    )
    session.add(sleep)
    await session.flush()
    session.add_all(
        [
            Question(
                passage_id=sleep.id,
                order_index=1,
                type="mcq",
                prompt="During which stage does the brain consolidate memories?",
                options=["Light sleep", "Deep sleep", "REM sleep", "Waking"],
                correct_answer="REM sleep",
                explanation="The passage says memory consolidation occurs during REM sleep.",
                difficulty="medium",
            ),
            Question(
                passage_id=sleep.id,
                order_index=2,
                type="true_false_notgiven",
                prompt="Adults need exactly ten hours of sleep each night.",
                options=["true", "false", "not_given"],
                correct_answer="false",
                explanation="The passage recommends seven to nine hours for adults.",
                difficulty="medium",
            ),
            Question(
                passage_id=sleep.id,
                order_index=3,
                type="short_answer",
                prompt="Which hormone rises in the evening to promote sleep?",
                options=None,
                correct_answer="melatonin",
                explanation="Melatonin levels rise in the evening.",
                difficulty="medium",
            ),
        ]
    )

    # A harder passage for learners who progress.
    urban = Passage(
        title="Urban Green Spaces",
        body=_SEED_BODY_URBAN,
        exam_type="academic",
        difficulty="hard",
        topic="environment",
        word_count=len(_SEED_BODY_URBAN.split()),
        source="seed",
    )
    session.add(urban)
    await session.flush()
    session.add_all(
        [
            Question(
                passage_id=urban.id,
                order_index=1,
                type="mcq",
                prompt="What do urban parks reduce, according to the passage?",
                options=[
                    "Rainfall",
                    "Air pollution and surface temperature",
                    "Population growth",
                    "Traffic accidents",
                ],
                correct_answer="Air pollution and surface temperature",
                explanation="The passage states parks lower air pollution and surface temperatures.",
                difficulty="hard",
            ),
            Question(
                passage_id=urban.id,
                order_index=2,
                type="true_false_notgiven",
                prompt="Every city in the study increased its park funding.",
                options=["true", "false", "not_given"],
                correct_answer="not_given",
                explanation="Funding decisions are never discussed in the passage.",
                difficulty="hard",
            ),
            Question(
                passage_id=urban.id,
                order_index=3,
                type="short_answer",
                prompt="Shade from trees has what effect on cooling costs?",
                options=None,
                correct_answer="reduce",
                explanation="The passage says shade from trees reduces cooling costs.",
                difficulty="hard",
            ),
        ]
    )
    await session.flush()


class ReadingController:
    @staticmethod
    async def _questions(session: AsyncSession, passage_id: str) -> list[Question]:
        rows = await session.scalars(
            select(Question)
            .where(Question.passage_id == passage_id)
            .order_by(Question.order_index)
        )
        return list(rows)

    @classmethod
    async def get_passage(
        cls,
        session: AsyncSession,
        user_id: str,
        difficulty: str | None,
        exam_type: str,
    ) -> PassageResponse:
        await _ensure_seeded(session)
        if difficulty is None or difficulty == "adaptive":
            difficulty, _, _ = await resolve_difficulty(session, user_id, "reading")
        # Random pick so repeated practice varies the content.
        passage = await session.scalar(
            select(Passage)
            .where(Passage.exam_type == exam_type, Passage.difficulty == difficulty)
            .order_by(func.random())
            .limit(1)
        )
        if passage is None:
            passage = await session.scalar(
                select(Passage)
                .where(Passage.exam_type == exam_type)
                .order_by(func.random())
                .limit(1)
            )
        if passage is None:
            passage = await session.scalar(
                select(Passage).order_by(func.random()).limit(1)
            )
        if passage is None:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND, detail="No passages available"
            )
        questions = await cls._questions(session, passage.id)
        return PassageResponse(
            id=passage.id,
            title=passage.title,
            body=passage.body,
            exam_type=passage.exam_type,
            difficulty=passage.difficulty,
            topic=passage.topic,
            word_count=passage.word_count,
            questions=[
                QuestionPublic(
                    id=q.id,
                    type=q.type,
                    prompt=q.prompt,
                    options=q.options,
                )
                for q in questions
            ],
        )

    @classmethod
    async def _grade(
        cls, questions: list[Question], answers: dict[str, Any]
    ) -> tuple[int, list[PerQuestionResult]]:
        raw = 0
        per_question: list[PerQuestionResult] = []
        for q in questions:
            submitted = answers.get(q.id)
            correct = is_correct(submitted, q.correct_answer)
            if correct:
                raw += 1
            per_question.append(
                PerQuestionResult(
                    question_id=q.id,
                    type=q.type,
                    correct=correct,
                    submitted=submitted,
                    correct_answer=q.correct_answer,
                    explanation=q.explanation,
                )
            )
        return raw, per_question

    @classmethod
    async def submit(
        cls, session: AsyncSession, user: User, payload: ReadingSubmitRequest
    ) -> ReadingResultResponse:
        passage = await session.get(Passage, payload.passage_id)
        if passage is None:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND, detail="Passage not found"
            )
        questions = await cls._questions(session, passage.id)
        total = len(questions)
        raw, per_question = await cls._grade(questions, payload.answers)
        band = reading_band(raw, total, passage.exam_type)

        attempt = ReadingAttempt(
            user_id=user.id,
            passage_id=passage.id,
            answers=payload.answers,
            raw_score=raw,
            total_questions=total,
            band=band,
        )
        session.add(attempt)
        wrong_tags = list(
            dict.fromkeys(pq.type for pq in per_question if not pq.correct)
        )
        if wrong_tags:
            await WeaknessService.record(session, user.id, "reading", wrong_tags)
        await session.flush()
        return ReadingResultResponse(
            attempt_id=attempt.id,
            passage_id=passage.id,
            raw_score=raw,
            total_questions=total,
            band=band,
            per_question=per_question,
        )

    @classmethod
    async def get_attempt(
        cls, session: AsyncSession, user: User, attempt_id: str
    ) -> ReadingResultResponse:
        attempt = await _attempts.get_owned(session, attempt_id, user.id)
        questions = await cls._questions(session, attempt.passage_id)
        _, per_question = await cls._grade(questions, attempt.answers)
        return ReadingResultResponse(
            attempt_id=attempt.id,
            passage_id=attempt.passage_id,
            raw_score=attempt.raw_score,
            total_questions=attempt.total_questions,
            band=attempt.band,
            per_question=per_question,
        )
